# Generated by Django 3.2.7 on 2021-09-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotacionPeliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='imdbID',
            field=models.TextField(default='', max_length=50),
        ),
    ]
