# Generated by Django 3.2.7 on 2021-09-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotacionPeliculas', '0003_alter_peliculas_votos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='votos',
            field=models.IntegerField(),
        ),
    ]
